version: '3.8'

services:
  weston:
    image: torizon/weston-am62:4
    container_name: weston
    network_mode: host
    cap_add:
      - CAP_SYS_TTY_CONFIG
    volumes:
      - /dev:/dev
      - /tmp:/tmp
      - /run/udev/:/run/udev/
    device_cgroup_rules:
      - 'c 4:* rmw'
      - 'c 13:* rmw'
      - 'c 226:* rmw'
      - 'c 10:223 rmw'
    command: --developer
    restart: unless-stopped

  crank:
    image: cranksoftware/ti62-sb_8_2-wayland-base-am62_4:v0.1
    container_name: crank
    volumes:
      - /tmp:/tmp
      - /dev/dri:/dev/dri
      - /var/run/dbus:/var/run/dbus
    device_cgroup_rules:
      - 'c 226:* rmw'
    restart: no
